name: pet-adoption automated tests
run-name: ${{ github.actor }} is testing out pet-adoption automated tests

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Run-Test-Suite:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]
        node-version: [16.x, 22.x, node]
        
    steps:
      - run: echo "This job is now running on a ${{ matrix.os }}"
      - run: |
          echo "Branch name: ${{ github.ref }}; Repository: ${{ github.repository }}."
      
      - name: Check out the latest code from repository.
        uses: actions/checkout@v4
      

      - name: Setup Node.js ${{ matrix.node-version }} on ${{ runner.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  

 
      - name: List repository files
        run: ls ${{ github.workspace }}


      - name: Install dependencies
        run: npm ci  


      - name: Run test suite
        env:
          APP_KEYS: ${{ secrets.APP_KEYS }}              
          API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}  
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }} 
          TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }} 
          JWT_SECRET: ${{ secrets.JWT_SECRET }}  
        run: |
          echo "Starting test suite..."
          npm test || echo "Tests failed on ${{ matrix.os }}"


      - name: Display job status
        run: |
          STATUS="${{ job.status }}"
          echo "Job status: $STATUS"
